services:
  - type: web
    name: innovation-x-lab-frontend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: innovation-x-lab-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
